// Template: Models (ApiModel.t4) version 5.0

// This code was generated by AMF Server Scaffolder

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace CH09_RamlClient.Api.Models
{
    public partial class Expanded
    {
        

        [Required]
        [MaxLength(0)]
        [MinLength(0)]
		[JsonProperty("count")]
        public decimal Count { get; set; }
    } // end class

} // end Models namespace

