// Template: Base Controller (ApiControllerBase.t4) version 5.0

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Http;
using System.Web.Http.Description;
using CH09_RamlClient.Api.Models;

// Do not modify this file. This code was generated by AMF Server Scaffolder

namespace CH09_RamlClient.Api
{
    [RoutePrefix("v1/helloWorld")]
    public partial class v1HelloWorldController : ApiController
    {


/// <summary>
		/// /helloWorld
		/// </summary>
		/// <returns>HelloWorldGet200</returns>
        [ResponseType(typeof(HelloWorldGet200))]
        [HttpGet]
        [Route("helloWorld")]
        public virtual async Task<IHttpActionResult> GetBase()
        {
            // Do not modify this code
                        return await ((Iv1HelloWorldController)this).Get();
                    }
    }
}
